spring:
  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:rbparams
    data: classpath:db/first/data.sql

second:
  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:second
    data: classpath:db/second/data.sql
